import { IRecurso } from "./types";

// Lista inicial de recursos
const recursosIniciais: IRecurso[] = [
  // FRONTEND
  {
    id: 1,
    titulo: "Rocketseat",
    descricao: "Plataforma brasileira com trilhas de React, Node.js e muito mais.",
    url: "https://app.rocketseat.com.br/",
    categoria: "Frontend",
    concluido: false,
    salvo: false,
  },
  {
    id: 2,
    titulo: "Alura",
    descricao: "Maior plataforma de cursos de tecnologia do Brasil, em português.",
    url: "https://www.alura.com.br/",
    categoria: "Frontend",
    concluido: false,
    salvo: false,
  },
  {
    id: 3,
    titulo: "Origamid",
    descricao: "Cursos brasileiros de UI Design, CSS e JavaScript do zero ao avançado.",
    url: "https://www.origamid.com/",
    categoria: "Frontend",
    concluido: false,
    salvo: true,
  },
  {
    id: 4,
    titulo: "Felipe Deschamps — YouTube",
    descricao: "Canal brasileiro com conteúdo sobre programação, carreira e tecnologia.",
    url: "https://www.youtube.com/@FilipeDeschamps",
    categoria: "Frontend",
    concluido: false,
    salvo: false,
  },
  {
    id: 5,
    titulo: "Código Fonte TV",
    descricao: "Canal no YouTube que explica conceitos de tecnologia de forma simples.",
    url: "https://www.youtube.com/@codigofontetv",
    categoria: "Frontend",
    concluido: false,
    salvo: false,
  },
  // BACKEND
  {
    id: 6,
    titulo: "Curso.dev",
    descricao: "Plataforma do Filipe Deschamps focada em fundamentos de programação.",
    url: "https://curso.dev/",
    categoria: "Backend",
    concluido: false,
    salvo: false,
  },
  {
    id: 7,
    titulo: "Fernanda Kipper — YouTube",
    descricao: "Canal com tutoriais de Java, Spring Boot e desenvolvimento backend.",
    url: "https://www.youtube.com/@FernandaKipper",
    categoria: "Backend",
    concluido: false,
    salvo: false,
  },
  {
    id: 8,
    titulo: "Loiane Groner",
    descricao: "Blog e canal com cursos gratuitos de Java, Angular e TypeScript.",
    url: "https://loiane.com/",
    categoria: "Backend",
    concluido: false,
    salvo: false,
  },
  {
    id: 9,
    titulo: "Dev Soutinho",
    descricao: "Canal com conteúdos de Node.js, Next.js e boas práticas de backend.",
    url: "https://www.youtube.com/@devsoutinho",
    categoria: "Backend",
    concluido: false,
    salvo: false,
  },
  // DEVOPS
  {
    id: 10,
    titulo: "LinuxTips",
    descricao: "Treinamentos brasileiros de Docker, Kubernetes e DevOps.",
    url: "https://www.linuxtips.io/",
    categoria: "DevOps",
    concluido: false,
    salvo: false,
  },
  {
    id: 11,
    titulo: "Fabricio Veronez — YouTube",
    descricao: "Canal referência em Kubernetes, Docker e pipelines de CI/CD no Brasil.",
    url: "https://www.youtube.com/@fabricioveronez",
    categoria: "DevOps",
    concluido: false,
    salvo: false,
  },
  {
    id: 12,
    titulo: "School of Net — DevOps",
    descricao: "Cursos em português de infraestrutura, Docker e automação.",
    url: "https://www.schoolofnet.com/",
    categoria: "DevOps",
    concluido: false,
    salvo: false,
  },
  // BANCO DE DADOS
  {
    id: 13,
    titulo: "DIO",
    descricao: "Plataforma gratuita com cursos de SQL, NoSQL, MySQL e MongoDB.",
    url: "https://www.dio.me/",
    categoria: "Banco de Dados",
    concluido: false,
    salvo: false,
  },
  {
    id: 14,
    titulo: "W3Schools — SQL Tutorial",
    descricao: "Tutorial gratuito de SQL com exemplos práticos e exercícios online.",
    url: "https://www.w3schools.com/sql/",
    categoria: "Banco de Dados",
    concluido: false,
    salvo: false,
  },
  {
    id: 15,
    titulo: "Bóson Treinamentos",
    descricao: "Canal com tutoriais gratuitos de SQL e banco de dados.",
    url: "https://www.youtube.com/@bosontreinamentos",
    categoria: "Banco de Dados",
    concluido: false,
    salvo: false,
  },
  {
    id: 16,
    titulo: "Otávio Miranda — SQL",
    descricao: "Curso gratuito de MySQL e modelagem de banco de dados em português.",
    url: "https://www.youtube.com/@otaviomiranda",
    categoria: "Banco de Dados",
    concluido: false,
    salvo: false,
  },
  // SEGURANÇA
  {
    id: 17,
    titulo: "Desec Security",
    descricao: "Escola brasileira especializada em segurança da informação.",
    url: "https://desecsecurity.com/",
    categoria: "Segurança",
    concluido: false,
    salvo: false,
  },
  {
    id: 18,
    titulo: "Hacking na Web",
    descricao: "Blog e canal sobre segurança ofensiva, pentest e OWASP em português.",
    url: "https://www.hackingnawe.com.br/",
    categoria: "Segurança",
    concluido: false,
    salvo: false,
  },
  {
    id: 19,
    titulo: "Gabriel Pato — YouTube",
    descricao: "Canal brasileiro sobre hacking ético, segurança e privacidade digital.",
    url: "https://www.youtube.com/@gabrielpato",
    categoria: "Segurança",
    concluido: false,
    salvo: false,
  },
  // IA & ML
  {
    id: 20,
    titulo: "Deep Learning Book BR",
    descricao: "Livro gratuito em português sobre Machine Learning e IA.",
    url: "https://www.deeplearningbook.com.br/",
    categoria: "IA & ML",
    concluido: false,
    salvo: false,
  },
  {
    id: 21,
    titulo: "Sandeco — YouTube",
    descricao: "Canal brasileiro sobre Inteligência Artificial e Machine Learning.",
    url: "https://www.youtube.com/@sandeco",
    categoria: "IA & ML",
    concluido: false,
    salvo: false,
  },
  {
    id: 22,
    titulo: "IA Expert Academy",
    descricao: "Plataforma brasileira com cursos de IA, Python e ciência de dados.",
    url: "https://iaexpert.academy/",
    categoria: "IA & ML",
    concluido: false,
    salvo: false,
  },
];

export default recursosIniciais;